apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: tempo

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: TraceID
          datasourceUid: tempo
          matcherRegex: "trace_id[\"']?:\\s*[\"']?(\\w+)[\"']?"
          url: "/explore?orgId=1&left=%5B%22now-30m%22,%22now%22,%22tempo%22,%7B%22query%22:%22%7B+resource.service_name+%3D+%5C%22$${service_name}%5C%22+%26%26+.traceID+%3D+%5C%22$${__value.raw}%5C%22+%7D%22,%22queryType%22:%22traceql%22%7D%5D"

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
      spanMetrics:
        datasourceUid: prometheus
      search:
        hide: false
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceId: true
        tags: ["service_name", "service.name"]
      tracesToMetrics:
        datasourceUid: prometheus
        spanAttributes: [service_name, service.name]