// Code generated by mockery v2.52.2. DO NOT EDIT.

package outismocks

import (
	outis "github.com/Brisanet/outis"
	mock "github.com/stretchr/testify/mock"
)

// WatcherOption is an autogenerated mock type for the WatcherOption type
type WatcherOption struct {
	mock.Mock
}

type WatcherOption_Expecter struct {
	mock *mock.Mock
}

func (_m *WatcherOption) EXPECT() *WatcherOption_Expecter {
	return &WatcherOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *WatcherOption) Execute(_a0 *outis.Watch) {
	_m.Called(_a0)
}

// WatcherOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type WatcherOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *outis.Watch
func (_e *WatcherOption_Expecter) Execute(_a0 interface{}) *WatcherOption_Execute_Call {
	return &WatcherOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *WatcherOption_Execute_Call) Run(run func(_a0 *outis.Watch)) *WatcherOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*outis.Watch))
	})
	return _c
}

func (_c *WatcherOption_Execute_Call) Return() *WatcherOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *WatcherOption_Execute_Call) RunAndReturn(run func(*outis.Watch)) *WatcherOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewWatcherOption creates a new instance of WatcherOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWatcherOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *WatcherOption {
	mock := &WatcherOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
