// Code generated by mockery v2.52.2. DO NOT EDIT.

package outismocks

import mock "github.com/stretchr/testify/mock"

// wrappedError is an autogenerated mock type for the wrappedError type
type wrappedError struct {
	mock.Mock
}

type wrappedError_Expecter struct {
	mock *mock.Mock
}

func (_m *wrappedError) EXPECT() *wrappedError_Expecter {
	return &wrappedError_Expecter{mock: &_m.Mock}
}

// Unwrap provides a mock function with no fields
func (_m *wrappedError) Unwrap() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// wrappedError_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type wrappedError_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *wrappedError_Expecter) Unwrap() *wrappedError_Unwrap_Call {
	return &wrappedError_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *wrappedError_Unwrap_Call) Run(run func()) *wrappedError_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *wrappedError_Unwrap_Call) Return(_a0 error) *wrappedError_Unwrap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *wrappedError_Unwrap_Call) RunAndReturn(run func() error) *wrappedError_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// newWrappedError creates a new instance of wrappedError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newWrappedError(t interface {
	mock.TestingT
	Cleanup(func())
}) *wrappedError {
	mock := &wrappedError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
